import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Lexend } from "next/font/google";

// Configuração da fonte Lexend do Google Fonts
const mainFontFamily = Lexend({
  weight: ["300", "700"],
  subsets: ["latin"],
});

// Metadados
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout principal
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${mainFontFamily.className} antialiased w-full h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
